# Configuration file for jekyll

# exclude version-control files from output dir
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor
  - CNAME

gems:
  - jekyll-sitemap

defaults:
  -
    scope:
      path: ""
      type: "drafts"
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "default"

# GitHub style
markdown: kramdown
kramdown:
  # GFM
  input: GFM
  # but without hard-breaks
  hard_wrap: false
